NEW HOMEworK
Maslik001/itstep pull request #4
Opened 2021-11-14 11:54 UTC by Maslik001

Привел ДЗ в соответствие с ТЗ 
Случайно выставил в SmartGit отслеживание своей ветки и залив в GH-PAGES/ORIGIN ---- поэтому с первого раза залил уже в ветку GH-PAGE - прошу извинения (ошибок нет, возможно начинаю осознавать как работает git) 
Проверьте пожалуйста новую версию ДЗ. 
Заранее спасибо и извините за некорректную работу с Git.

2021-11-15 20:58 UTC, itstep-mog requested changes
Работа понравилась. См. комментарии, исправляй и объединяй ветки

2021-11-15 20:58 UTC, itstep-mog commented on Medium_tree.html
> +    <ol>
А где этот тег закрывается?

2021-11-15 20:58 UTC, itstep-mog commented on Medium_tree.html
> +        </ul>
Тег `ul` должен быть вложен внутрь` li`. Тоже самое вниз по коду.

2021-11-15 20:58 UTC, itstep-mog commented on Small_tree.html
>          </ul>
Тег `ul` должен быть вложен внутрь` li`. Тоже самое вниз по коду.

2021-11-16 08:14 UTC, Maslik001 commented on Medium_tree.html
> +    <ol>
исправил

2021-11-16 08:16 UTC, Maslik001 commented on Medium_tree.html
> +        </ul>
не понял ошибки

2021-11-16 08:17 UTC, Maslik001 commented on Small_tree.html
>          </ul>
не понял ошибки

2021-11-16 13:58 UTC, merged