Task 1.3
Maslik001/itstep pull request #5
Opened 2021-11-19 07:03 UTC by Maslik001

Pull to main my Task 1.3

2021-11-21 17:00 UTC, itstep-mog requested changes
Нужны доработки

2021-11-21 17:00 UTC, itstep-mog commented on Big_tree.html
>                  <li><font color="red"><b>Matpol</b></font></li>
Стилизация через css

2021-11-21 17:00 UTC, itstep-mog commented on Big_tree.html
>                  <li><font color="red"><b>180cm</b></font></li>
Стилизация через css

2021-11-21 17:00 UTC, itstep-mog commented on Big_tree.html
>                  <li><font color="red"><b>Pvc</b></font></li>
Стилизация через css

2021-11-21 17:00 UTC, itstep-mog commented on Big_tree.html
>                  <li><font color="red"><b>Green</b></font></li>
Стилизация через css

2021-11-21 17:00 UTC, itstep-mog commented on Big_tree.html
>                  <li><font color="red"><b>No</b></font></li>
Стилизация через css

2021-11-21 17:00 UTC, itstep-mog commented on Big_tree.html
> +        ✓ the set includes: tree, stand, cardboard box.</a>
Заменить галочку на спецсимвол `&#10003;`

2021-11-21 17:00 UTC, itstep-mog commented on Big_tree.html
> +    </a>
Посмотри назначение `<a>`

2021-11-21 17:00 UTC, itstep-mog commented on Big_tree.html
> +    <div class="footer"> <div class="container"><span class="sub">© Все права защищены <a href="https://mogilev.itstep.by">ItStep</a> 2021</span></div>
Второй закрывающийся div?

2021-11-21 17:00 UTC, itstep-mog commented on Contacts.html
> +<div <div class="container">
????

2021-11-21 17:00 UTC, itstep-mog commented on catalog.html
> +                <button id="Medium">Specification</button></form>
Необходимость <form> под вопросом.

2021-11-21 17:00 UTC, itstep-mog commented on catalog.html
> +                        ✓ the set includes: tree, stand, cardboard box.</a>
????

2021-11-24 12:00 UTC, Maslik001 reviewed
fixed

2021-11-24 12:00 UTC, merged